import { BrokerProfile } from './types';
import { darwinProfileImage } from './profile-images';

export const mockBrokers: BrokerProfile[] = [
  {
    id: 'darwin-hanneman',
    fullName: 'Darwin Hanneman',
    agencyName: 'Moonshine Capital',
    slug: 'darwin-hanneman',
    shortBio: 'Straightforward equipment finance and business funding guidance for owners who need a practical next move, not a pitch deck and a prayer.',
    city: 'Washington',
    state: 'DC',
    websiteUrl: 'https://www.distilledfunding.com',
    publicEmail: '',
    whyChooseYou: 'Darwin brings a calm, relationship-driven approach to equipment finance, fleet needs, and business-critical capital decisions. The goal is not to throw every funding product at the wall and hope something sticks. The goal is to help business owners understand what may actually fit, where approval odds may be stronger, and how to move without wasting weeks in lender theater.',

    industries: ['Construction', 'Transportation', 'Service Businesses', 'Real Estate'],
    fundingTypes: ['Equipment Financing', 'Vehicle & Fleet Financing', 'Revenue-Based Funding', 'Business Term Loans', 'SBA Options'],
    urgencyCategory: 'standard',
    serviceArea: ['Nationwide'],
    speedToContact: 'Within 2 hours',
    minimumDealSize: 50000,
    maximumDealSize: 5000000,
    primaryCtaType: 'apply',
    proofPoints: ['Over $50M deployed', 'Fast approval process', 'Transparent terms'],
    bestFitClients: 'Established businesses with minimum $500k annual revenue looking for equipment upgrades or expansion capital.',
    verticals: ['Construction', 'Transportation', 'Service Businesses', 'Real Estate'],
    fundingSpecialties: ['Equipment Financing', 'Vehicle & Fleet Financing', 'Revenue-Based Funding', 'Business Term Loans', 'SBA Options'],

    primaryCta: {
      label: 'Apply Now',
      url: 'https://bit.ly/fundingwithdarwin',
      variant: 'primary',
      trackingId: 'cta_darwin_hanneman'
    },
    secondaryCta: {
      label: 'Book a Call',
      url: 'https://distilledfunding.com/book-online',
      variant: 'secondary',
      trackingId: 'cta_darwin_call'
    },
    primaryCtaLink: 'https://bit.ly/fundingwithdarwin',
    ctaLabel: 'Apply Now',
    profileImage: darwinProfileImage,

    approvalStatus: 'approved',
    isActive: true,
    featuredFlag: true,
    featuredBroker: true,
    brokerStatus: 'active',
  },
  {
    id: '1',
    fullName: 'Jane Doe',
    agencyName: 'Velocity Capital',
    slug: 'jane-doe',
    shortBio: 'Ex-founder turned capital allocator. I get deals done when banks say no.',
    city: 'Austin',
    state: 'TX',
    websiteUrl: 'https://example.com',
    publicEmail: 'jane@velocitycapital.com',
    whyChooseYou: 'No fluff. No slow banks. Just operators who know how to move money.',

    industries: ['SaaS', 'Manufacturing', 'Technology'],
    fundingTypes: ['SaaS Revenue', 'Equipment Finance', 'Bridge Loans'],
    urgencyCategory: 'fast',
    serviceArea: ['TX', 'CA', 'NY', 'FL'],
    speedToContact: 'Within 1 hour',
    minimumDealSize: 100000,
    maximumDealSize: 10000000,
    primaryCtaType: 'apply',
    proofPoints: ['Specialized in SaaS metrics', 'Non-dilutive capital', 'Founder-friendly terms'],
    bestFitClients: 'SaaS and tech companies with $1M+ ARR looking to extend runway without giving up equity.',
    verticals: ['SaaS', 'Manufacturing', 'Technology'],
    fundingSpecialties: ['SaaS Revenue', 'Equipment Finance', 'Bridge Loans'],

    primaryCta: {
      label: 'Apply for Funding',
      url: 'https://example.com/apply',
      variant: 'primary',
      trackingId: 'cta_jane_doe'
    },
    primaryCtaLink: 'https://example.com/apply',

    approvalStatus: 'approved',
    isActive: true,
    featuredFlag: true,
    featuredBroker: true,
    profileImage: 'https://i.pravatar.cc/300?img=5',
  },
  {
    id: '2',
    fullName: 'John Smith',
    agencyName: 'Ironclad Funding',
    slug: 'john-smith',
    shortBio: 'We fund heavy machinery and real estate. Fast, aggressive, reliable.',
    city: 'Chicago',
    state: 'IL',
    websiteUrl: 'https://example.com',
    publicEmail: 'john@ironcladfunding.com',
    whyChooseYou: 'We don\'t waste your time. If the numbers make sense, we wire within 48 hours.',

    industries: ['Construction', 'Real Estate', 'Logistics'],
    fundingTypes: ['Equipment Finance', 'Real Estate', 'SBA Loans'],
    urgencyCategory: 'standard',
    serviceArea: ['Midwest USA', 'IL', 'OH', 'MI'],
    speedToContact: 'Same business day',
    minimumDealSize: 250000,
    maximumDealSize: 15000000,
    primaryCtaType: 'apply',
    proofPoints: ['Deep real estate expertise', 'Flexible collateral requirements', 'Quick closing times'],
    bestFitClients: 'Real estate developers and construction firms needing quick access to bridge capital or equipment financing.',
    verticals: ['Construction', 'Real Estate', 'Logistics'],
    fundingSpecialties: ['Equipment Finance', 'Real Estate', 'SBA Loans'],

    primaryCta: {
      label: 'Submit Deal',
      url: 'https://example.com/apply',
      variant: 'primary',
      trackingId: 'cta_john_smith'
    },
    primaryCtaLink: 'https://example.com/apply',

    approvalStatus: 'approved',
    isActive: true,
    featuredFlag: false,
    featuredBroker: false,
    profileImage: 'https://i.pravatar.cc/300?img=11',
  },
  {
    id: '3',
    fullName: 'Sarah Jenkins',
    agencyName: 'Neon Growth Partners',
    slug: 'sarah-jenkins',
    shortBio: 'Specializing in e-commerce inventory and marketing capital.',
    city: 'New York',
    state: 'NY',
    websiteUrl: 'https://example.com',
    publicEmail: 'sarah@neongrowth.com',
    whyChooseYou: 'Built for founders who do not have time for institutional theater.',

    industries: ['E-commerce', 'Retail', 'DTC'],
    fundingTypes: ['Revenue Based', 'Working Capital'],
    urgencyCategory: 'fast',
    serviceArea: ['Global'],
    speedToContact: 'Within 30 minutes',
    minimumDealSize: 10000,
    maximumDealSize: 2000000,
    primaryCtaType: 'apply',
    proofPoints: ['Data-driven underwriting', 'Connect store directly', 'Capital in 24 hours'],
    bestFitClients: 'E-commerce brands needing inventory or ad spend capital ahead of peak seasons.',
    verticals: ['E-commerce', 'Retail', 'DTC'],
    fundingSpecialties: ['E-commerce', 'Revenue Based', 'Working Capital'],

    primaryCta: {
      label: 'Get Funded Fast',
      url: 'https://example.com/apply',
      variant: 'primary',
      trackingId: 'cta_sarah_jenkins'
    },
    primaryCtaLink: 'https://example.com/apply',

    approvalStatus: 'approved',
    isActive: true,
    featuredFlag: true,
    featuredBroker: true,
    profileImage: 'https://i.pravatar.cc/300?img=9',
  },
  {
    id: '4',
    fullName: 'Marcus Vance',
    agencyName: 'Vance Capital Advisors',
    slug: 'marcus-vance',
    shortBio: 'Strategic financing for mid-market acquisitions and expansions.',
    city: 'Miami',
    state: 'FL',
    websiteUrl: 'https://example.com',
    publicEmail: 'marcus@vancecapital.com',
    whyChooseYou: 'I bring 20 years of structuring experience to the table. I solve complex capital stacks.',

    industries: ['Healthcare', 'B2B Services', 'Enterprise'],
    fundingTypes: ['M&A', 'Bridge Loans', 'Term Loans'],
    urgencyCategory: 'complex',
    serviceArea: ['North America'],
    speedToContact: 'Next business day',
    minimumDealSize: 1000000,
    maximumDealSize: 50000000,
    primaryCtaType: 'book_call',
    proofPoints: ['Complex structuring capabilities', 'Network of institutional partners', 'End-to-end M&A advisory'],
    bestFitClients: 'Mid-market companies ($10M - $100M revenue) seeking acquisition financing or undergoing major recapitalization.',
    verticals: ['Healthcare', 'B2B Services', 'Enterprise'],
    fundingSpecialties: ['M&A', 'Bridge Loans', 'Term Loans'],

    primaryCta: {
      label: 'Book Consultation',
      url: 'https://example.com/apply',
      variant: 'primary',
      trackingId: 'cta_marcus_vance'
    },
    primaryCtaLink: 'https://example.com/apply',

    approvalStatus: 'approved',
    isActive: true,
    featuredFlag: false,
    featuredBroker: false,
    profileImage: 'https://i.pravatar.cc/300?img=12',
  }
];
