import { BrokerProfile } from './types';

export const mockBrokers: BrokerProfile[] = [
  {
    id: '1',
    fullName: 'Jane Doe',
    agencyName: 'Velocity Capital',
    slug: 'jane-doe',
    shortBio: 'Ex-founder turned capital allocator. I get deals done when banks say no.',
    city: 'Austin',
    state: 'TX',
    websiteUrl: 'https://example.com',
    publicEmail: 'jane@velocitycapital.com',
    whyChooseYou: 'No fluff. No slow banks. Just operators who know how to move money.',
    fundingSpecialties: ['SaaS Revenue', 'Equipment Finance', 'Bridge Loans'],
    primaryCtaLink: 'https://example.com/apply',
    approvalStatus: 'approved',
    isActive: true,
    featuredBroker: true,
    profileImage: 'https://i.pravatar.cc/300?img=5',
  },
  {
    id: '2',
    fullName: 'John Smith',
    agencyName: 'Ironclad Funding',
    slug: 'john-smith',
    shortBio: 'We fund heavy machinery and real estate. Fast, aggressive, reliable.',
    city: 'Chicago',
    state: 'IL',
    websiteUrl: 'https://example.com',
    publicEmail: 'john@ironcladfunding.com',
    whyChooseYou: 'We don\'t waste your time. If the numbers make sense, we wire within 48 hours.',
    fundingSpecialties: ['Equipment Finance', 'Real Estate', 'SBA Loans'],
    primaryCtaLink: 'https://example.com/apply',
    approvalStatus: 'approved',
    isActive: true,
    featuredBroker: false,
    profileImage: 'https://i.pravatar.cc/300?img=11',
  },
  {
    id: '3',
    fullName: 'Sarah Jenkins',
    agencyName: 'Neon Growth Partners',
    slug: 'sarah-jenkins',
    shortBio: 'Specializing in e-commerce inventory and marketing capital.',
    city: 'New York',
    state: 'NY',
    websiteUrl: 'https://example.com',
    publicEmail: 'sarah@neongrowth.com',
    whyChooseYou: 'Built for founders who do not have time for institutional theater.',
    fundingSpecialties: ['E-commerce', 'Revenue Based', 'Working Capital'],
    primaryCtaLink: 'https://example.com/apply',
    approvalStatus: 'approved',
    isActive: true,
    featuredBroker: true,
    profileImage: 'https://i.pravatar.cc/300?img=9',
  },
  {
    id: '4',
    fullName: 'Marcus Vance',
    agencyName: 'Vance Capital Advisors',
    slug: 'marcus-vance',
    shortBio: 'Strategic financing for mid-market acquisitions and expansions.',
    city: 'Miami',
    state: 'FL',
    websiteUrl: 'https://example.com',
    publicEmail: 'marcus@vancecapital.com',
    whyChooseYou: 'I bring 20 years of structuring experience to the table. I solve complex capital stacks.',
    fundingSpecialties: ['M&A', 'Bridge Loans', 'Term Loans'],
    primaryCtaLink: 'https://example.com/apply',
    approvalStatus: 'approved',
    isActive: true,
    featuredBroker: false,
    profileImage: 'https://i.pravatar.cc/300?img=12',
  }
];
